version: "3.9"

services:
  skyforskning:
    build: .
    container_name: skyforskning
    ports:
      - "127.0.0.1:8010:8010"
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - mariadb
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8010/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

  mariadb:
    image: mariadb:10.11
    container_name: mariadb_skyforskning
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: Klokken!12!?!
      MARIADB_DATABASE: skyforskning
      MARIADB_USER: skyforskning
      MARIADB_PASSWORD: Klokken!12!?!
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  mariadb_data:
